### ISSUE TITLE
I like this project, but

### ISSUE THREAD

**Issue by dev-bz** [REDxEYE/OVL_IO#2]
Some data decoding errors, like vertex, uv, faces. I try to analyze the data inside, then I know it is so hard

**Comment by REDxEYE** [comment]
Feel free to make pull requests with fixes and etc

**Comment by dev-bz** [comment]
Hi, that bone's rotation is not a euler, it is a quaternion, so that format 'fff' must be 'ffff', and maybe w = -w.
