### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [REDxEYE/OVL_IO#3]
Hi, just opening an issue here to get in touch. Been working on a pyffi-based OVL reader + blender plugin targeting JWE & PZ. Current state of the art - importing parrot.ovl with all model & texture data & banis animation into blender:
[Animated screengrab](https://i.imgur.com/wuVj5TS.mp4)

Maybe we can pool forces?

**Comment by REDxEYE** [comment]
I'm in

**Comment by HENDRIX-ZT2** [comment]
Great! Are you on discord? That's where discussion's been taking place.
Here's an invite to a common server:
https://discord.gg/WVdagy
